show databases; -- intilaly shows system databases 
-- create database
create database company_db;

-- to check which databse your in if u have muliple databases 
select database();

-- create only if missing
create database if not exists company_db1;

-- show databses

show databases;

-- use databse

use company_db;
-- drop database 

drop database company_db1;
-- drop databse if exists

drop database if exists company_db1;
-- create table 

create table employess(
emp_id int,
emp_name varchar(50),
salary int
);

-- show table, shows Lists tables in the current database.

show tables;

-- describe table, Shows columns, types, NULL rules and keys.

desc employess;

-- create statement, Shows the table definition generated by MySQL

show create table employess;

-- add column, Adds a column to an existing table.

alter table company_db.employess add column phone varchar(20);  -- imp for real time 

-- add multiple columns, Adds several columns at once.

alter table employess
add column city varchar(20),
add column country varchar(20);

-- add column at first, Adds a column at the beginning of the table definition.

alter table employess add column gender varchar(20) FIRST;

desc employess;

-- add column at particular position

alter table employess add column dob date after emp_name;

-- raname table

rename table employess to staff;

desc staff;

-- rename table with alter
alter table staff rename to employess; -- imp

desc employess;

-- rename column 

alter table employess rename column emp_name to  full_name;

-- modify, if want to change data type cloumn

alter table employess modify column full_name varchar(100);

-- change, rename column and redefine a column.

alter table employess change column full_name emp_name varchar(50);

-- drop a column

alter table employess drop column dob; -- imp

-- drop multiple columns 

alter table employess
drop column phone,
drop column country;

desc employess;

-- insert data 

-- single insert
insert into company_db.employess values('M',1,'Mahesh',5000);

-- multiple inserts 
insert into company_db.employess values('M',2,'harish',7000),
('F',3,'divya',6000);


insert into company_db.employess values('M',4,'Manohar',5000);

-- insert based on column names

insert into company_db.employess (gender,emp_id,emp_name,salary) values ('F',5,'siri',5000);

insert into company_db.employess (gender,emp_id,emp_name) values ('F',5,'siri');

insert into company_db.employess (emp_id,gender,emp_name,salary) values (7,'M','malli',7000);

-- select all columns

select * from company_db.employess;

-- select only required columns

select emp_id,emp_name from company_db.employess;

-- distinct, Removes duplicate result rows.

select distinct emp_name from company_db.employess;

-- column alias, Temporarily renames an output column.

select emp_id as e_id ,emp_name as e_name  from company_db.employess;
